import Head from "next/head"
// import Image from "next/image"
// import styles from "../styles/Home.module.css"
import styled from "@emotion/styled"
import { useRouter } from "next/router"

import Main from "../design-system/Main"
import { Button, ButtonsContainer } from "../design-system/Buttons"

const GameTitle = styled.h1`
  font-family: "Life Savers";
  font-weight: 900;
  font-size: 3rem;
  color: #fff;
  text-align: center;
  color: var(--primary);
`
export default function Home() {
  const router = useRouter()

  const goToContentWarning = () => router.push("/content-warning")

  const goToPlayerSetup = () => router.push("/players")

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Main>
        <GameTitle>Funishment</GameTitle>

        <ButtonsContainer>
          <Button
            backgroundColor="var(--secondary)"
            hoverBackgroundColor="var(--secondary-shade)"
            onClick={goToContentWarning}
          >
            Start
          </Button>

          {/* <Button onClick={goToPlayerSetup}>Continue</Button> */}
        </ButtonsContainer>
      </Main>
    </>
  )
}
